name: me_warp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
        pip install telebot
        pip install retrying
        pip install cryptography
        pip install datetime
        pip install requests
   
    - name: Run script
      run: python ipv6.py
