name: me_warp

on:
  push:
    branches: [ "main" ]
  schedule: 
    - cron: '*/180 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
   
    - name: Run script
      run: python warp2.py
    - name: Commit and push changes
      run: |          
          git config --global user.email "darknessm.427@gmail.com"
          git config --global user.name "darknessm427"
          git config credential.helper store
          git add -A
          git commit -m "Automatic update"
          git push
